mkdir src\main\java
mkdir src\main\resources\dev
mkdir src\main\resources\production
mkdir src\main\resources\public
mkdir src\main\resources\test
mkdir src\main\webapp\WEB-INF
mkdir test\java
mkdir test\resources
mkdir config